[profile.default]
# Number of retries for failed tests
retries = 0

# Show test output for failed tests
failure-output = "immediate"

# Show test output for successful tests
success-output = "never"

# Run tests in parallel
test-threads = "num-cpus"

# Timeout for each test
slow-timeout = { period = "60s", terminate-after = 3 }

[profile.ci]
# CI-specific settings
retries = 2
failure-output = "immediate"
success-output = "never"
test-threads = "num-cpus"

# Fail fast on CI
fail-fast = false

# Show detailed output
status-level = "all"

[profile.default.junit]
# Enable JUnit XML output
path = "target/nextest/junit.xml"
